DROP DATABASE BD_T2_VILLENA;
CREATE DATABASE BD_T2_VILLENA;
USE BD_T2_VILLENA;

CREATE TABLE categoria(
    IDE_CAT INT          NOT NULL, 
    DES_CAT VARCHAR(50) NOT NULL,
    FRE_COM VARCHAR(25)  NOT NULL, -- FRECUENCIA DE COMPRA
    PRIMARY KEY(IDE_CAT)
);

CREATE TABLE productos(
    IDE_PRO INT         NOT NULL,
    NOM_PRO VARCHAR(50) NOT NULL,
    IDE_CAT INT         NOT NULL,
    STK_ACT INT         NOT NULL, -- STOCK ACTUAL
    CONSTRAINT TB_PK PRIMARY KEY(IDE_PRO),
    CONSTRAINT FK_TO_CATEGORIA FOREIGN KEY(IDE_CAT) REFERENCES categoria(IDE_CAT)
);

CREATE TABLE inventario(
    NRO_INV INT     AUTO_INCREMENT,
    FEC_INV DATE    NOT NULL, -- FECHA
    IDE_PRO INT     NOT NULL,
    COS_ING DOUBLE  NOT NULL, -- COSTO INGRESO
    CONSTRAINT TB_PK PRIMARY KEY(NRO_INV),
    CONSTRAINT FK_TO_PRODUCTO FOREIGN KEY(IDE_PRO) REFERENCES productos(IDE_PRO)
);

INSERT INTO categoria (IDE_CAT,DES_CAT, FRE_COM) VALUES 
(1, 'Mediano', '10 cada semana'),
(2, 'Liviano', '25 cada dia');

INSERT INTO productos(IDE_PRO, NOM_PRO, IDE_CAT, STK_ACT) VALUES
(1, 'Laptop Acer Revolution', 1,150),
(2, 'Tarjeta Grafica NVIDIA RTX4060 ', 2,200);

INSERT INTO inventario(NRO_INV, FEC_INV, IDE_PRO, COS_ING) VALUES
(1, now(), 1, 34.5),
(2, now(), 2, 15.5);